### ISSUE TITLE
clarification of the functionality.

### ISSUE THREAD

**Issue by ihsinme** [jurajsic/DQBDD#2]
Good afternoon.
I am confused about the use of tmpnam functions in your code.

https://github.com/jurajsic/DQBDD/blob/ef37d202b19f200f11e1f345794dc99050cbbd3e/libs/hqspre/formula_findHidden.cpp#L261

If you want to get an unused name on the system.
do you consider the threat, the file can be created between scan and open?

thanks for taking the time to answer.

**Comment by jurajsic** [comment]
Hi! The function tmpnam is used in library HQSpre that I did not implement so I do not know why it is used. Also, from the way that DQBDD uses HQSpre, the function solveSAT (where tmpnam is used) is never called.
