### ISSUE TITLE
Cannot parse the exampe QCIR file

### ISSUE THREAD

**Issue by 5nizza** [jurajsic/DQBDD#4]
The readme files describes the following example:
```
$ cat /tmp/readme_example.qcir 
#QCIR-G14 10
forall(1, 2)
exists(3)
forall(4)
exists(5)
depend(6, 1, 4)
output(7)
8 = and(-6, 3)
9 = or(-1, -8, 5)
10 = or(-2, -4, 5)
7 = and(9, 10)

$ ./dqbdd_linux_static /tmp/readme_example.qcir 
Parsing
ERROR: First line of (D)QCIR file should start with '#QCIR-14'
```

If `#QCIR-G14 10` is replaced by `#QCIR-14`, it works.

**Comment by jurajsic** [comment]
Hi, it seems to be a mistake in a readme file, I think it should be `#QCIR-14`. But the website for the definition of QCIR format does not work currently, so I cannot check which is correct.

**Comment by 5nizza** [comment]
I used the static version provided by the release. The latest version parses it just fine.  Thanks.
